services:
  rabbit:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitData/data:/var/lib/rabbitmq
      - ./data/rabbitData/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
      - RABBITMQ_DEFAULT_VHOST=rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 30s
      retries: 10

  receiver_app:
    image: receiver_app
    ports:
      - "3001:3000"
    volumes:
      - ./data/appData:/data
    environment:
      - RABBITMQ_HOST=rabbit
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=pass
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      rabbit:
        condition: service_healthy

  entrance_consumer:
    image: entrance_consumer
    environment:
      - RABBITMQ_HOST=rabbit
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=pass
      - PYTHONHTTPSVERIFY=0
    volumes:
      - ./data/config:/config:ro
    depends_on:
      receiver_app:
        condition: service_healthy

  # exit_consumer:
  #   image: exit-consumer
  #   environment:
  #     - RABBITMQ_HOST=rabbit
  #     - RABBITMQ_USER=user
  #     - RABBITMQ_PASS=pass
  #   depends_on:
  #     receiver_app:
  #       condition: service_healthy

  nginx:
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx
      - ./data/cert/:/cert
    healthcheck:
      test: ["CMD","pgrep","nginx"]
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      rabbit:
        condition: "service_healthy"
      receiver_app:
        condition: "service_healthy"
